### ISSUE TITLE
Encoding Error

### ISSUE THREAD

**Issue by rafaelss** [fnando/tagger#2]
My application is throwing encoding errors when I try to do this:

```
p = Post.new
p.tagged_with = "popularização"

Encoding::CompatibilityError: incompatible encoding regexp match (Windows-31J regexp with UTF-8 string)
from my_app/vendor/ruby/1.9.1/gems/tagger-0.1.1/lib/tagger/tag.rb:39:in `gsub!'
from my_app/vendor/ruby/1.9.1/gems/tagger-0.1.1/lib/tagger/tag.rb:39:in `parse'
from my_app/vendor/ruby/1.9.1/gems/tagger-0.1.1/lib/tagger/active_record.rb:43:in `parsed_tags'
from my_app/vendor/ruby/1.9.1/gems/tagger-0.1.1/lib/tagger/active_record.rb:29:in `tagged_with='
```

I was about to fix by myself and send a pull request later, but I have no idea what is the best solution for this case.

**Comment by fnando** [comment]
Just fixed this issue. You can have it by installing the version 0.1.2.
